domain:
  mode: nip
  
  #used only if mode=nip
  suffix: nip.io
  ip: 192.168.31.127   # REQUIRED for nip mode

  #used only if mode=static
  name: example.com

certificate:
  mode: selfsigned   # selfsigned | provided
  name: code-server-certificate

  # used only if mode=provided
  # those files must be under /nginx/certs/
  cert_file: fullchain.pem
  key_file: privkey.pem

auth_users:
  test_user:
    username: test_user
    password: password
    email: test_user@example.com
    groups:
      - admins

services:
  auth:
    is_auth: true
    container_name: authelia
    host_prefix: auth
    port: 9091
    requires_auth: false

  static:
    container_name: static-site
    host_prefix: test
    port: 80
    requires_auth: true
    #used if require_auth=true, default is admins
    allowed_groups: 
      - admins
      - devs
