---
- name: Ensure kubeconfig directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy Kubernetes admin config to user kubeconfig
  ansible.builtin.copy:
    src: "{{ kubernetes_kubeconfig_path }}"
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'